---
- hosts: all
  become: true
  tasks:

  - name: install updates in ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: install docker in ubuntu
    apt:
      name: docker.io
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: start docker 
    service:
      name: docker
      state: restarted

  - name: add docker group to current user
    ansible.builtin.group:
      name: dockerfile 
      state: present
  
   
